name: edit_calendar_event_view
description: Opens native edit calendar event view
version: 0.3.3+33
repository: https://github.com/chris-wolf/edit_calendar_event_view


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.18.0
  device_calendar:
    path: ../device_calendar
  flutter:
    sdk: flutter
  flutter_timezone: ^3.0.1
  intl: ^0.20.2
  macos_ui: ^2.0.7
  plugin_platform_interface: ^2.1.8
  sprintf: ^7.0.0
  timezone: ^0.9.4
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


screenshots:
  - description: 'Edit event view for iOS'
    path: example/screenshots/edit_calendar_event_view_ios_screenshot.png
