name: edit_calendar_event_view
description: Opens native edit calendar event view
version: 0.2.0+20
repository: https://github.com/chris-wolf/edit_calendar_event_view


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.cwolf.editCalendarEventView.edit_calendar_event_view
        pluginClass: EditCalendarEventViewPlugin
      ios:
        pluginClass: EditCalendarEventViewPlugin

screenshots:
  - description: 'Edit event view for iOS'
    path: example/screenshots/edit_calendar_event_view_ios_screenshot.png
